# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: applications.azuread.upbound.io/v1beta2
kind: Application
metadata:
  name: example
spec:
  forProvider:
    displayName: example-alper
